### ISSUE TITLE
Could you please add the image optimization code for nuts/durian?

### ISSUE THREAD

**Issue by tuobaye11** [eigenvivek/DiffDRR#128]
Could you please add the image optimization code for nuts/durian? We plan to use DR To detect whether nuts/durian have mold or bugs.

**Comment by eigenvivek** [comment]
Hi tuobaye11, I'm not familiar with nuts/durian, can you please explain what that is?

**Comment by tuobaye11** [comment]
In factories, it is often inefficient for workers to manually check nuts or durians for bad fruit. We studied the DR /CT method to check for bad fruit.

**Comment by eigenvivek** [comment]
Hi @tuobaye11, the code should work for any CT scan, regardless of whether it's a medical image or of anything else. I hope the package proves useful, and feel free to open a new issue if any specific questions come up.
