### ISSUE TITLE
DRR intensity inconsistency.

### ISSUE THREAD

**Issue by BraveDistribution** [eigenvivek/DiffDRR#130]
Thank you for this wonderful and easy-to-use package. I wonder what I am doing wrong when the generated DRR is a bit different color than a fluoroscopy taken at the intervention. 

I have a dataset from the article: 1911.07042] Automatic Annotation of Hip Anatomy in Fluoroscopy for Robust and Efficient 2D/3D Registration

(https://arxiv.org/abs/1911.07042) - could you give me an example with one abdominal CT?

I have provided MHA CT here ([18-2799.mha - Google Drive](https://drive.google.com/file/d/1NZWCJ-6FnKHK7XSLWxCn1x_s1nF8ufbN/view?usp=sharing)) - (I will have to delete this later, but you can find full dataset at the page [3. ipcai_2020_full_res_data.zip - Johns Hopkins Research Data Repository](https://archive.data.jhu.edu/file.xhtml?persistentId=doi:10.7281/T1/IFSXNV/EAN9GH)).

The geometry seems to be ok, but the resulting image is off (like black and white intensity switched). 

Could you hint me how to move on forward and to improve the DRR? I want to use it for 2d-3d registration.

![image](https://user-images.githubusercontent.com/36101458/231182600-91dae559-62da-458d-b605-0d48be4ac896.png)

Furthermore, is it possible to also add the geometry example? if we have x,y,z axis (detector is perpendicular to Z axis), then what is the out-of-plane angle and what is gantry angle?

from my experiments, it seems that gamma is in-plane angle (rotation of the projection), gamma is gantry angle etc.

**Comment by BraveDistribution** [comment]
https://github.com/eigenvivek/DiffDRR/blob/bf287deebb4292a009a4566cee566213cbc84a74/notebooks/tutorials/spherical.ipynb

this describes it well.

**Comment by eigenvivek** [comment]
Hi, thank you for the kind words, glad the package has been useful for you!

I'll have more time to look at this closely at the end of the week. In the meantime, the first question that comes to mind is how are you storing the imaging data in memory?

Specifically, I've noticed that there are sometimes negative values in CT scans (eg, to denote voxels with air). Do you have these in your scan? If yes, did you zero them out? Otherwise they'll contribute incorrect negative values to the generated DRR. This is just my convention for dealing with negative values in CT scans. It seems like there are other strategies, and maybe one might be more appropriate (see this [other issue](https://github.com/eigenvivek/DiffDRR/issues/100)).

**Comment by BraveDistribution** [comment]
I don't have any negative values in the CT.

The values range from to (0, 170.32936).

**Comment by hemmer** [comment]
Is this just that the images are inverses? These examples from a similar library might help, or a different inversion. 

https://github.com/arcadelab/deepdrr/blob/846e701884d44b397acdee80a71f34370ddd9db0/deepdrr/projector/projector.py#L217

https://github.com/arcadelab/deepdrr/blob/846e701884d44b397acdee80a71f34370ddd9db0/deepdrr/utils/__init__.py#L199

**Comment by eigenvivek** [comment]
@hemmer They do look inverted! Do you know why people use the `neglog` transform? I've started seeing it in other CT/X-ray datasets, but don't know if it has any physical/mathematical meaning.

**Comment by eigenvivek** [comment]
Thanks for these references, very helpful!

**Comment by eigenvivek** [comment]
Yup, the discrepancy is due to needing a neglog.

Preprocessed images from the deepfluoro dataset are cropped to remove the collimator effects and then neglog transformed. ([link](https://github.com/rg2/DeepFluoroLabeling-IPCAI2020/issues/3))

**Comment by BraveDistribution** [comment]
Thanks @eigenvivek . I am gonna try your algorithm with new data soon!
