### ISSUE TITLE
2D-3D registration example is outdated

### ISSUE THREAD

**Issue by BraveDistribution** [eigenvivek/DiffDRR#131]
Hi, 

Readme at https://github.com/eigenvivek/DiffDRR points to an example of 6DoF to: The full example is available at [experiments/registration](https://github.com/eigenvivek/DiffDRR/blob/main/experiments/registration).

`from diffdrr.metrics import XCorr2, geodesic`

Geodesic doesn't exist anymore in diffdrr so it fails on import.

thanks.

**Comment by eigenvivek** [comment]
Yup, you're right. The API in this example is old and needs to be updated. Thanks for catching that!

You're welcome to submit a PR if you'd like! Otherwise I can do it later this week.

**Comment by BraveDistribution** [comment]
I will try to find time to create a PR. Furthermore, as we discussed in the second issue it would be great to have a 3D-2D registration (CT, fluoro) on a public dataset (link here: https://github.com/eigenvivek/DiffDRR/issues/130).

I am not sure how to perform 3D-2D registration, since the example file creates a "true" DRR and then perturbates the parameters to create another DRR (and the similarity metrics are computed, then the predicted DRR is changed, etc.)

**Comment by eigenvivek** [comment]
this code has been removed from the current version of the package, and an up-to-date version of the registration pipeline is available in the documentation https://vivekg.dev/DiffDRR/tutorials/optimizers.html
