### ISSUE TITLE
Parameter issue

### ISSUE THREAD

**Issue by shenao1994** [eigenvivek/DiffDRR#161]
I referred to the example. I found that the latest version of diffdrr does not have the parameter **bone'_ Attention_ Multiplier=0.0** .

**Comment by eigenvivek** [comment]
Hi Shen, sorry about that. `bone_attenuation_multiplier` is currently in the master branch, but not in the latest version released on PyPI. I'll release a new version today and ping you when it's out.

**Comment by shenao1994** [comment]
> Hi Shen, sorry about that. `bone_attenuation_multiplier` is currently in the master branch, but not in the latest version released on PyPI. I'll release a new version today and ping you when it's out.

OK! Thank you!

**Comment by eigenvivek** [comment]
Just released the updated version, which you should be able to pip install! Feel free to reopen this issue if you still have any trouble.
