### ISSUE TITLE
Batch Generate Issues

### ISSUE THREAD

**Issue by shenao1994** [eigenvivek/DiffDRR#163]
Hello! I am planning to apply **DiffDRR** to **Pytorch**. During training, the training set is combined with **batch size** input, but it seems that **DiffDRR** can only generate one drr at a time. At present, I can only set the **batch size** to 1. I'm not sure if DiffDRR can be combined with batch size for batch generation. I hope you can have some sample code. Thank you!

**Comment by eigenvivek** [comment]
Hi @shenao1994, `diffdrr` can generate batches of DRRs. The key is to pass a batch of parameters to the renderer.

See this example: https://vivekg.dev/DiffDRR/tutorials/introduction.html#batched-drr-synthesis

**Comment by shenao1994** [comment]
Thank you!

**Comment by shenao1994** [comment]
> Hi @shenao1994, `diffdrr` can generate batches of DRRs. The key is to pass a batch of parameters to the renderer.
> 
> See this example: https://vivekg.dev/DiffDRR/tutorials/introduction.html#batched-drr-synthesis

Thank you!
