### ISSUE TITLE
Refactor `diffdrr.utils.Transform3d` and unify with `DiffPose`

### ISSUE THREAD

**Issue by eigenvivek** [eigenvivek/DiffDRR#183]
`DiffDRR` and `DiffPose` implement different classes for rigid transforms of point clouds, originally inherited from `pytorch3d.transforms.Transform3d`. Having two classes is annoying, as it also results in two sets of conversion functions. Also PyTorch3D's implementation uses a right-handed matrix convention, which almost no one else uses, so it'd be good to move away from that.

- [x] Implement a unified `RigidTransform` class in `DiffDRR`
- [x] Have one set of `convert` functions for transforming between different representations of SE(3)
- [x] Make sure all calls in `diffdrr.detector` work with the new `RigidTransform` class
- [ ] Make sure nothing breaks in `DiffPose`

**Comment by gmedan** [comment]
You should check out [pypose](https://pypose.org/) which is way nicer than pytorch3d, and sticks to common conventions. `pypose.se3` should be able to do all the heavy lifting under the hood of `RigidTransform`, or even replace it entirely - it is a `torch.tensor` subclass supporting batches and Lie Algebra auto differentiation. 
pypose also features autodiff jacobians for bundle adjustment and jacobian-based solvers such as LM.

**Comment by eigenvivek** [comment]
what the heck how have i never heard of this library - it looks awesome! excited to try it out.

it does look like it can do most things I need. only thing missing that seems to be conversions between different Euler angles conventions, which is an easy patch.

this is a treat - thanks for pointing it out.

**Comment by gmedan** [comment]
I only recently found out about it too, and it's so much better than pytorch3d, but lacks the rendering pipeline pytorch3d has for nerfs. I wrote some bundle adjustment solvers with pypose, now I'm trying to get it to work with diffdrr

**Comment by gmedan** [comment]
Will do. Thanks for publishing diffdrr and diffpose, just started with them but they look great
