### ISSUE TITLE
How to get the intrinsic and the extrinsix matrix from the projection parameters

### ISSUE THREAD

**Issue by jeanRassaire** [eigenvivek/DiffDRR#190]
Hi,

I am using  diffdrr for 3D reconstruction. My drrs are generated with known parameters (sdr, delx, height, width, rotation and translation). Suppose that I generated my drr from the volume V with parameters sdr, delx, height (h), width (w), rotation (R) and translation (t)

I would  to project any 3D voxel (X, Y, Z) of the volume (V) into the 2D, to get a 2D pixel (x/w, y/w) of the image (drr), as illustrated in the attached. To do this, I need to know the intrinsic and extrinsic matrices. 

How can I calculate the intrinsic and extrinsic matrices from the projection parameters (sdr, delx, h, w, R (yaw, pitch, roll) and t)?

![image](https://github.com/eigenvivek/DiffDRR/assets/145753695/2ccd4bf8-2ce7-453b-a451-247b18387b74)

**Comment by eigenvivek** [comment]
Hi @jeanRassaire ,

**For the extrinsic matrix,** you can use the `diffdrr.pose.convert` function. You pass your Euler angles and translations (and the Euler angle convention you're using), and the function will return a `diffdrr.pose.RigidTransform` object. This object has an attribute `.matrix`, which is your extrinsic matrix with an extra row at the bottom. 

In pseudocode:
```python
from diffdrr.pose import convert

pose = convert(rotation, translation, convention="ZYX")
extrinsic = pose.matrix[:, :3]
```

Alternatively, `diffdrr.pose.RigidTransform` is a `torch.nn.Module` that can handle the first matrix-vector product for you:
```python
import torch
from diffdrr.pose import convert

pts = torch.randn(1, 100, 3)
pose = convert(rotation, translation, convention="ZYX")
transformed_pts = pose(pts)
```

**For the intrinsic matrix,** you use the relationship `focal_length = 2 * source_to_detector_radius` (i.e., `f = 2 * sdr`) to construct the intrinsic matrix:

```python
intrinsic = torch.tensor(
    [
        [2 * sdr * delx, 0, 0],
        [0, 2 * sdr * delx, 0],
        [0, 0, 1],
    ]
)
```

**Comment by rassaire** [comment]
Thanks. That's even what I did, but I was not sure.

**Comment by eigenvivek** [comment]
Hi @rassaire , this makes sense! Not all the voxels within a volume will be projected onto the detector plane, depending on your intrinsic and extrinsic parameters.

**One sanity check: when you render the DRR from these intrinsic/extrinsic parameters are all parts of the anatomy visible in the image?**

[This website](https://ksimek.github.io/2013/08/13/intrinsic/) really helped me understand camera intrinsics. Using the interactive applet at the bottom, you will be able to see that for high values of the focal length, some parts of the ball are clipped out of the imaging plane. These correspond to parts of the ball outside of your image dimension range.

Also, here's a vectorized way to compute the projections of all your points (i.e., without using `for` loops). Should be a lot faster in pytorch!

```python
import torch
from diffdrr.pose import random_rigid_transform

nx = torch.arange(128, dtype=torch.float32)
pts = torch.meshgrid(nx, nx, nx, indexing="xy")
pts = torch.stack(pts, dim=-1).reshape(1, -1, 3)

f = torch.randn(1)
intrinsic = torch.tensor(
    [
        [f, 0, 0],
        [0, f, 0],
        [0, 0, 1],
    ]
)
extrinsic = random_rigid_transform()

transformed_pts = extrinsic(pts)
torch.einsum("ij,bnj->bni", intrinsic, transformed_pts)
```

**Comment by eigenvivek** [comment]
> yes, when I render the DRR from these intrinsic/extrinsic parameters, all parts of the anatomy are visible in the image.

Hm. Can you try `f = 2 * sdr` instead and see if that produces what you expect?

**Comment by rassaire** [comment]
@eigenvivek 

I've just tried that but it doesn't work either. If you have an example that works, please share it with me so I can check what's wrong.

**Comment by eigenvivek** [comment]
@rassaire can you try this
```python
intrinsic = torch.tensor(
    [
        [-2 * sdr / delx, 0              , height / 2],
        [0              , -2 * sdr / dely, width / 2],
        [0              , 0              , 1]
    ]
)
```

**Comment by eigenvivek** [comment]
[DiffPose](https://github.com/eigenvivek/DiffPose) has working 2D/3D projection of points.

[Here's an example](https://vivekg.dev/DiffPose/api/deepfluoro.html#fiducial-markers) of the project working on the `DeepFluoro` dataset.

[This 3D rendering](https://vivekg.dev/DiffPose/experiments/render.html) shows 3D points in space (purple) being projected onto the imaging plane (green). In theory, we should be able to use all voxel locations as 3D points and project them appropriately with this function.

**Comment by rassaire** [comment]
> @rassaire can you try this
> 
> ```python
> x0 = 0.0
> y0 = 0.0
> intrinsic = torch.tensor(
>     [
>         [-2 * sdr / delx, 0.0            , h / 2 - x0 / delx],
>         [0.0            , -2 * sdr / dely, w / 2 - y0 / dely],
>         [0.0            , 0.0            , 1.0              ],
>     ]
> )
> ```

@eigenvivek  thanks again. I have tried this, but it does not either.

**Comment by rassaire** [comment]
> @rassaire can you try this
> 
> ```python
> x0 = 0.0
> y0 = 0.0
> intrinsic = torch.tensor(
>     [
>         [-2 * sdr / delx, 0.0            , h / 2 - x0 / delx],
>         [0.0            , -2 * sdr / dely, w / 2 - y0 / dely],
>         [0.0            , 0.0            , 1.0              ],
>     ]
> )
> ```

@eigenvivek  thanks again. I tried this but it doesn't work either.

**Comment by rassaire** [comment]
@eigenvivek  I tried to see some code (fiducials_3d_to_projected_fiducials_3d) that uses the intrinsic matrix in diffpose for fluoroscopy datasets. However, I discovered that the intrinsic matrix is provided in the .h5 file.  So that didn't really help as what I want is to estimate them from the projection parameters.

**Comment by eigenvivek** [comment]
Hi @rassaire , the intrinsic matrices in that .h5 file are off the form above, so I was hoping they would solve your issue. I am not sure where the problem comes from at the moment.

I am a tad swamped with other obligations at the moment, but I can try to do this projection tomorrow. I'll let you know what I figure out.

Thanks for raising this important question - the camera projection matrix is something that we definitely need to figure out and will be a great addition to `DiffDRR`!

**Comment by rassaire** [comment]
> Hi @rassaire , the intrinsic matrices in that .h5 file are off the form above, so I was hoping they would solve your issue. I am not sure where the problem comes from at the moment.
> 
> I am a tad swamped with other obligations at the moment, but I can try to do this projection tomorrow. I'll let you know what I figure out.
> 
> Thanks for raising this important question - the camera projection matrix is something that we definitely need to figure out and will be a great addition to `DiffDRR`!

Thanks @eigenvivek. I hope to hear from you soon regarding that.

**Comment by eigenvivek** [comment]
Hi @rassaire , I think I've figured out how to do the projection. Turns out one more coordinate frame change was necessary.

Need a few more hours to write up everything, but here's a preliminary figure. Red dots are voxel centers, green dots are where they get projected to on the imaging plane. Will post the code to do the camera projection soon.

<img width="606" alt="Screenshot 2024-02-21 at 14 50 04" src="https://github.com/eigenvivek/DiffDRR/assets/29757116/e1209f09-0834-4f5a-811a-35649e8ed0e1">

**Comment by eigenvivek** [comment]
In this PR, I've added `diffdrr.DRR.perspective_projection`, which returns the 2D pixel coordinates `[x/w, y/w]`.

```python
def perspective_projection(
    self: DRR,
    pose: RigidTransform,
    pts: torch.Tensor,
):
    extrinsic = (
        pose.inverse().compose(self.detector.translate).compose(self.detector.flip_xz)
    )
    x = extrinsic(pts)
    x = torch.einsum("ij, bnj -> bni", self.detector.intrinsic, x)
    z = x[..., -1].unsqueeze(-1).clone()
    x = x / z
    return x[..., :2]
```

The transform `pose.inverse().compose(self.detector.translate).compose(self.detector.flip_xz)` does a coordinate shift to move points in anatomical coordinates to the camera coordinates. This is something we were missing earlier.

```python
# Anatomy to world coordinates
flip_xz = torch.tensor(
    [
        [0.0, 0.0, -1.0, 0.0],
        [0.0, 1.0, 0.0, 0.0],
        [1.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 1.0],
    ]
)
translate = torch.tensor(
    [
        [1.0, 0.0, 0.0, -self.sdr],
        [0.0, 1.0, 0.0, 0.0],
        [0.0, 0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0, 1.0],
    ]
)
```

The intrinsic matrix that we had before was correct
```python
intrinsic = torch.tensor(
    [
        [2 * sdr / delx, 0.0, x0 / delx - height / 2],
        [0.0, 2 * sdr / dely, y0 / dely - width / 2],
        [0.0, 0.0, 1.0],
    ]
)
```

**Comment by eigenvivek** [comment]
Just pulled this into `main`.  Please feel free to reopen this issue if you're still having any issues!

**Comment by shenao1994** [comment]
> In this PR, I've added `diffdrr.DRR.perspective_projection`, which returns the 2D pixel coordinates `[x/w, y/w]` corresponding to the 3D points `pts` at a camera pose `pose`.
> 
> ```python
> def perspective_projection(
>     self: DRR,
>     pose: RigidTransform,
>     pts: torch.Tensor,
> ):
>     extrinsic = (
>         pose.inverse().compose(self.detector.translate).compose(self.detector.flip_xz)
>     )
>     x = extrinsic(pts)
>     x = torch.einsum("ij, bnj -> bni", self.detector.intrinsic, x)
>     z = x[..., -1].unsqueeze(-1).clone()
>     x = x / z
>     return x[..., :2]
> ```
> 
> The transform `pose.inverse().compose(self.detector.translate).compose(self.detector.flip_xz)` does a coordinate shift to move points in anatomical coordinates to the camera coordinates. This is something we were missing earlier.
> 
> ```python
> # Anatomy to world coordinates
> flip_xz = torch.tensor(
>     [
>         [0.0, 0.0, -1.0, 0.0],
>         [0.0, 1.0, 0.0, 0.0],
>         [1.0, 0.0, 0.0, 0.0],
>         [0.0, 0.0, 0.0, 1.0],
>     ]
> )
> translate = torch.tensor(
>     [
>         [1.0, 0.0, 0.0, -self.sdr],
>         [0.0, 1.0, 0.0, 0.0],
>         [0.0, 0.0, 1.0, 0.0],
>         [0.0, 0.0, 0.0, 1.0],
>     ]
> )
> ```
> 
> The intrinsic matrix that we had before was correct
> 
> ```python
> intrinsic = torch.tensor(
>     [
>         [2 * sdr / delx, 0.0, x0 / delx - height / 2],
>         [0.0, 2 * sdr / dely, y0 / dely - width / 2],
>         [0.0, 0.0, 1.0],
>     ]
> )
> ```

Hi @eigenvivek, I want to know if the offsets x0 and y0 in the intrinsic matrix can be obtained in diffdrr? Or is x0 and y0 set by oneself?

**Comment by shenao1994** [comment]
> Hi @rassaire , I think I've figured out how to do the projection. Turns out one more coordinate frame change was necessary.
> 
> Need a few more hours to write up everything, but here's a preliminary figure. Red dots are voxel centers, green dots are where they get projected to on the imaging plane. Will post the code to do the camera projection soon.
> 
> <img alt="Screenshot 2024-02-21 at 14 50 04" width="606" src="https://private-user-images.githubusercontent.com/29757116/306755681-e1209f09-0834-4f5a-811a-35649e8ed0e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDczMjUsIm5iZiI6MTcwOTU0NzAyNSwicGF0aCI6Ii8yOTc1NzExNi8zMDY3NTU2ODEtZTEyMDlmMDktMDgzNC00ZjVhLTgxMWEtMzU2NDllOGVkMGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEwMTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MzgyOGRjZWM4MDkyYTNiNzUxNDI1YWEwMWE2M2U0MzZkYzJiYzZlYWQ5NzdiNDc5MGM1YmFiZTYxODYyMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bUoULIerrnb3BY9WFPu0811bjR24EEdFVC-cn2suLgk">

Hi, @eigenvivek Can you share this code? I am also working on projecting CT volume pixels. Thank you.

**Comment by eigenvivek** [comment]
Hi @shenao1994 , in the `main` branch of `DiffDRR` (i.e., not released on PyPI yet), there's the functions for projecting points into 2D (`DRR.perspective projection`) and lifting projections back into 3D (`DRR.inverse_projection`):

https://github.com/eigenvivek/DiffDRR/blob/0fd1bd4199824645215d08f9f9371e29febaace7/diffdrr/drr.py#L176-L215

I don't know what you mean by "voxel center". Can you please clarify?

**Comment by shenao1994** [comment]
> Hi @shenao1994 , in the `main` branch of `DiffDRR` (i.e., not released on PyPI yet), there's the functions for projecting points into 2D (`DRR.perspective projection`) and lifting projections back into 3D (`DRR.inverse_projection`):
> 
> https://github.com/eigenvivek/DiffDRR/blob/0fd1bd4199824645215d08f9f9371e29febaace7/diffdrr/drr.py#L176-L215
> 
> I don't know what you mean by "voxel center". Can you please clarify?

What you said about "Red dots are voxel centers".

**Comment by eigenvivek** [comment]
My first thought would be to look at the tensor `pts` and make sure they are actually the bounding box for the CT.

In my example, `pts` is formed as follows:

```python
nx = torch.arange(dims[0], dtype=torch.float32) * spacing[0]
ny = torch.arange(dims[1], dtype=torch.float32) * spacing[1]
nz = torch.arange(dims[2], dtype=torch.float32) * spacing[2]

pts = torch.meshgrid(nx, nx, nx, indexing="xy")
pts = torch.stack(pts, dim=-1).reshape(1, -1, 3)
```

**Comment by shenao1994** [comment]
> My first thought would be to look at the tensor `pts` and make sure they are actually the bounding box for the CT.
> 
> In my example, `pts` is formed as follows:
> 
> ```python
> nx = torch.arange(dims[0], dtype=torch.float32) * spacing[0]
> ny = torch.arange(dims[1], dtype=torch.float32) * spacing[1]
> nz = torch.arange(dims[2], dtype=torch.float32) * spacing[2]
> 
> pts = torch.meshgrid(nx, nx, nx, indexing="xy")
> pts = torch.stack(pts, dim=-1).reshape(1, -1, 3)
> ```

This is the point I extracted, essentially the vertex of the vertebral body bounding box.
![微信截图_20240305093157](https://github.com/eigenvivek/DiffDRR/assets/28835780/5e2d8f9d-5a28-4611-889f-00f533d09d0e)
![微信截图_20240305093112](https://github.com/eigenvivek/DiffDRR/assets/28835780/eaf139f2-742d-4032-9296-edc153891553)
I want to project the vertices onto the original DRR, and I have done center point displacement. The DRR of the vertebrae can cover the original DRR.
![微信截图_20240305093549](https://github.com/eigenvivek/DiffDRR/assets/28835780/0b0d7539-4d18-40d9-a837-12fb48378268)
But projecting only the vertices of the bounding box failed.

I'm wondering if it's because I used version 0.3.11 of **diffdrr** to generate images. However, the inner and outer parameter matrices I used were based on the latest code, which caused the projection to fail?

**Comment by eigenvivek** [comment]
@shenao1994 can you please pull the latest version of `diffdrr` from `main` and try that? I updated the intrinsic matrix code, I think that might fix your issue.

**Comment by shenao1994** [comment]
> @shenao1994 can you please pull the latest version of `diffdrr` from `main` and try that? I updated the intrinsic matrix code, I think that might fix your issue.

Thank you for your advice! I have done so, but there still seems to be a problem. I refer to the code in **diffpose**. It seems that one step of **lps2volume** transformation is needed. I am trying. But I still hope you can share this code, because I happen to be doing the same thing. I want to refer to it. Thank you!

![image](https://github.com/eigenvivek/DiffDRR/assets/28835780/809c3ae7-2c6a-4b59-bfb4-d2f15c1001cd)
