### ISSUE TITLE
3D binary segmentation projection

### ISSUE THREAD

**Issue by fedeface98** [eigenvivek/DiffDRR#191]
Hello,

I need to directly project in 2D a 3D CT segmentation (3D binary mask), Is there a way to do it with diffDRR?

Thanks a lot for sharing your work!

**Comment by eigenvivek** [comment]
Hi @fedeface98, this is a great idea! The way to do this would be to render a DRR from your 3D segmentation mask, and then threshold the rendered DRR. In theory, the only pixels in the DRR with intensity values > 0 are those whose ray intersected your object of interest.

 I haven't tried this myself yet, but I would be really curious if this approach works!

Now the very interesting question is could you do this with a multilabel segmentation map...

**Comment by fedeface98** [comment]
Thanks a lot for your answer!

I want to try this approach, because with DeepDRR it works! But I have a problem in the mapping between diffDRR and deepDRR, becuase in DeepDRR I set both 'source_to_isocenter_distance' and 'source_to_detector_distance', but in diffDRR I can just set sdr, is it right? and so source to isocenter distance is always sdr/2?

**Comment by eigenvivek** [comment]
Yup, in DiffDRR you just set the `sdr`. But the conversion is `sdr = source_to_detector_distance / 2` (since `sdr` is "source to detector _radius_)

**Comment by fedeface98** [comment]
The problem is that in deepDRR I'm setting both. So I can't find a mapping between the 2. 

I think I have also a problem with the mapping between DeepDRR and DiffDRR because I'm loading the data in nifti format, whereas in your example you used DICOM. Did you fin a mapping also with nifti volume?

**Comment by eigenvivek** [comment]
Hi @fedeface98 , I am not sure exactly how DeepDRR uses `source_to_isocenter_distance` and `source_to_detector_distance` (along with the `alpha` and `beta` parameters) to form the camera pose. Do you know where that code is located in their package? If you can find that, I can probably work out what the exact conversion is.

The [`metamorphisis.ipynb`](https://vivekg.dev/DiffDRR/tutorials/metamorphasis.html) has a tutorial for converting `DiffDRR -> DeepDRR`, but not the other way. Does this help you at all?

Also issues with NIFTI seem to have been resolved now. When you pass a volume to `DiffDRR`, you need to make sure the volume/spacing are ordered as `XYZ`, not `ZYX` (the default from `nibabel` and `SimpleITK`).

Finally, we fixed the weird blocky artifacts. When those appear, you should switch the rendering backend from `siddon` to `trilinear`. See [this issue](https://github.com/eigenvivek/DiffDRR/issues/172) for more explanation.

**Comment by fedeface98** [comment]
First of all, thanks a lot for your kindness!

The source_to_isocenter_distance  is set in the Mobile_carm.py in particular directly in the function camera3d_from_device: 
```python
def camera3d_from_device(self) -> geo.FrameTransform:
        """Get the camera3d frame from device coordinates

        The Z axis points from the source to the detector."""
        camera3d_from_arm = geo.FrameTransform.from_rt(
            translation=geo.point(
                0,
                -self.source_to_isocenter_horizontal_offset,
                self.source_to_isocenter_vertical_distance,
            )
        )
        if self.rotate_camera_left:
            camera3d_from_arm = (
                geo.frame_transform(Rotation.from_euler("z", 90, degrees=True))
                @ camera3d_from_arm
            )

        # This is a little hacky, since the "device" frame is now kind of wrong, and modeling this
        # C-arm wouldn't show the rotation about the principle ray, but it will work to rotate the
        # images produced.
        gamma_rotation = geo.frame_transform(
            Rotation.from_euler("z", self.gamma, degrees=False)
        )

        return gamma_rotation @ camera3d_from_arm @ self.arm_from_device
``` 

Unfortunately [metamorphisis.ipynb](https://vivekg.dev/DiffDRR/tutorials/metamorphasis.html) does not help me but I think because In this example you worked directrly with DICOM and me with nifti.

**Comment by eigenvivek** [comment]
No problem at all, I'm very happy to help!

Are you also using `source_to_isocenter_horizontal_offset = 0`?

Also what kind of object is `gamma_rotation @ camera3d_from_arm @ self.arm_from_device`? Is it a 4 x 4 transformation matrix? Please let me know - if it is, I can probably decode it into a camera pose that DiffDRR can use.

**Comment by fedeface98** [comment]
yes I am using source_to_isocenter_horizontal_offset = 0. 

gamma_rotation @ camera3d_from_arm @ self.arm_from_device is a 4x4 transformation matrix ! 

I think that source to isocenter distance is what you call sdr, and you suppose that source to detector distance is 2*sdr. If we can insert 2 separate variable so that source to detector distance is not 2*sdr, this should solve the issue.

**Comment by eigenvivek** [comment]
Can you please post an example of one of the 4x4 transformation matrices? I wrote some functions in DiffPose to convert a pose in DeepDRR convention to DiffDRR convention.

**Comment by fedeface98** [comment]
Yes sure! This is my whole projection matrix with rotation and translation = 0 :

```python
source_to_detector_distance=1120
source_to_isocenter_vertical_distance = 820

CameraProjection(  [[   2867.2           0.          256.       201081.16   ]
   [      0.         2867.2         256.      -198141.19   ]
   [      0.            0.            1.          694.33105]])
``` 


And this is the 'camera3d_from_device' 4x4 transformation matrix:

```python
FrameTransform(  [[   1.          0.          0.          8.137695]
   [   0.          1.          0.       -131.1     ]
   [   0.          0.          1.        694.33105 ]
   [   0.          0.          0.          1.      ]])
```

**Comment by eigenvivek** [comment]
Hi @fedeface98 I've given up trying to reconcile the transforms conventions between DiffDRR and DeepDRR. But, in the `nifti` development branch, I've added functionality to directly render segmentations from multilabel masks! Should be pulled into the main branch in a few weeks as part of a major update.
