### ISSUE TITLE
New version！

### ISSUE THREAD

**Issue by shenao1994** [eigenvivek/DiffDRR#193]
I have been using **DiffDRR** to train CNN for pose regression recently. During the training process, it is necessary to generate DRRs online. But this process consumes a lot of GPU resources. I see that you have recently updated the interpolation method, can it improve efficiency? And I want to know what modifications have been made to the new version, but I couldn't find the documentation. Thank you!

**Comment by eigenvivek** [comment]
Hi @shenao1994, glad to hear `DiffDRR` is still proving useful! Yeah, online DRR generation for pose regression is expensive -- I had to use an A6000 just to generate batch sizes of 8 DRRs on the fly!

You're right, we have a new rendering mode that uses trilinear interpolation to generate DRRs. I don't know if this is more or less efficient than Siddon's method, but it's certainly worth a shot.

I haven't written any documentation yet, but you can see how to use the new API at [this issue](https://github.com/eigenvivek/DiffDRR/issues/172#issuecomment-1935296094) and [this issue](https://github.com/eigenvivek/DiffDRR/issues/186).

The parameter that you can wiggle in the `diffdrr.DRR.forward` call is `n_points` (i.e., the number of points sampled along each ray for trilinear interpolation). Lower number of points will render DRRs faster and with a lower memory footprint, at the tradeoff of lower quality images (see [this example](https://github.com/eigenvivek/DiffDRR/issues/186#issuecomment-1935015881)).

Thanks for reminding me that I need to make a documentation notebook. For now, [the source code](https://github.com/eigenvivek/DiffDRR/blob/main/diffdrr/renderers.py#L117) is located here, which may also be helpful.

Let me know whatever questions you have!

**Comment by eigenvivek** [comment]
Hi @shenao1994 , I added a [section to the documentation](https://vivekg.dev/DiffDRR/tutorials/introduction.html#different-rendering-mode) describing how the trilinear interpolator works. Hope this answers your questions! If you have any more questions, feel free to reopen this issue or make a new one.
