### ISSUE TITLE
Questions about volume location

### ISSUE THREAD

**Issue by khh656** [eigenvivek/DiffDRR#198]
Hello, in the process of generating drr, is the position of the volume involved? What I mean is that there is [0020,0032](Image Position) in the DICOM file. At present, I found that the program does not use this information. If I want to add this information, what should I do? By the way, there is another question, which is what is the specific relationship between the description and definition of DiffDRR's coordinate system? What is its origin? I would be very grateful if you could answer!

**Comment by eigenvivek** [comment]
Hi @khh656, you're right that `DiffDRR` does not incorporate Image Position from the DICOM in any way. I'm pretty sure I use it in `DiffPose` (although Robert Grupp's original release preprocesses the data before I import it, so I'm not 100% confident that these are the same origins), but you could look at [this transform](https://github.com/eigenvivek/DiffPose/blob/fb75e13291b3064d177bbf362bf37568b3866086/diffpose/deepfluoro.py#L285-L294).

More generally, `DiffDRR`'s coordinate system is set up as such:
- I assume the CT lies in the positive orthant of 3D space (i.e., all of the CT data lies along the positive x-, y-, and z-axes).
- Anatomical coordinates, camera coordinates, and world coordinates are all the same reference frame, i.e., the origin is always `(0, 0, 0)` in 3D space.
- I initialize the X-ray source at `(0, 0, SDR)` and the center of the detector plane at `(0, 0, -SDR)`.
- If you want to visualize the 3D geometry of `DiffDRR` at a particular pose, you can use [the functions in this tutorial](https://vivekg.dev/DiffDRR/tutorials/visualization.html) and visually inspect to make sure it matches what you expect.

This is a really naive geometric set up. This part of `DiffDRR` was written before I really understood perspective geometry / anatomical coordinates, so there are a lot of improvements that can be made (see #192 , #199). The changes proposed in these issues are breaking changes, so I won't be implementing them before the MICCAI deadline... but probably sometime this semester, `DiffDRR` will exit alpha and I'll release a version `1.0.0` with major updates to the geometry.
