### ISSUE TITLE
'eps' is undefined in the function axis_angle_to_quaternion() in pose.py

### ISSUE THREAD

**Issue by YongzeYang** [eigenvivek/DiffDRR#203]
Hi @eigenvivek,

I found a bug in pose.py.  In the function axis_angle_to_quaternion, 'eps' is undefined (line 640). I guess it should be fixed by adding a statement 'eps = 1e-6' before (maybe another value like 1e-4).

Best wishes,
Yongze

**Comment by eigenvivek** [comment]
Hi @YongzeYang you're right thanks for the catch!
