### ISSUE TITLE
How can one provide a batched volume to the DRR generator?

### ISSUE THREAD

**Issue by jeanRassaire** [eigenvivek/DiffDRR#205]
Hello,

I am using the diffdrr. I have  a model capable of producing various 3D images as Torch tensors. I aim to provide a batch of volumes to the DRR generator. Is it feasible to do  this without resorting to looping?

**Comment by eigenvivek** [comment]
hi @jeanRassaire batched volumes is difficult (or maybe impossible) with the current implementation of diffdrr

right now, the renderer supports batched c-arm poses but only works with one volume

you would probably have to change the internal code to support batched volumes

one option would be to return drrs of the shape
`(volume) (pose) (channels) (height) (width)`

but this would probably require quite a few changes. i'll look into what specifically would need to be changed / if it would be a simple patch
