### ISSUE TITLE
got error when trying to run_backward on a loss computed from two drrs

### ISSUE THREAD

**Issue by jeanRassaire** [eigenvivek/DiffDRR#206]
Hello,

I have a model that generates 3D volumes. Then I calculate the drr from these volumes, then the loss between the generated drr and the 2D image. When I try to run_backward the loss to update the gradient , I get this error.
```Python
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.
```

When i use torch.autograd.set_detect_anomaly(True) to find the error,  it suggests that the error is comming from this line of code
```Python
weighted_voxels = voxels * step_length
```
After a few checks, I discovered that step_length had some nan values, which may be the cause of this problem.  

Do you understand this problem, and do you have any suggestions for solving it?

**Comment by eigenvivek** [comment]
the nan trick was used to compute all pixels in a drr in parallel. see this code:
https://github.com/eigenvivek/DiffDRR/blob/0e11ee243802c21892b00232223848342e6bc993/diffdrr/renderers.py#L33-L41

makes sense that it would cause an error for gradients. a simple fix for now would be to use `DRR(renderer="trilinear")` instead, which shouldn't have any nans

**Comment by jeanRassaire** [comment]
Thanks @eigenvivek , while "trilinear" deosn't have any nans, it also gives another error

```Python
one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor ] which is output 0 of DivBackward0, is at version 5; expected version 4 instead.
```

I  found that the error occurs here in the ```Python set_bone_attenuation_multiplier```:
```Python
 self.density /= self.density.max()
```

**Comment by eigenvivek** [comment]
sure that makes sense, so you'd have to rewrite the source code as
```python
self.density = self.density / self.density.max()
```

although in theory diffdrr can be used for volume reconstruction, the current library was not built with that in mind. so there are probably a few more of these little issues throughout the code that would need to be ironed out. thanks for catching these ones so far.

in a future release, i am planning to add explicit support for volume reconstruction.

**Comment by jeanRassaire** [comment]
thanks @eigenvivek

**Comment by eigenvivek** [comment]
Hi @jeanRassaire I added a tutorial showing how to do volume reconstruction with `DiffDRR`

https://vivekg.dev/DiffDRR/tutorials/reconstruction.html

**Comment by jeanRassaire** [comment]
thanks @eigenvivek .
