### ISSUE TITLE
type error generating DRR

### ISSUE THREAD

**Issue by sarbabi** [eigenvivek/DiffDRR#223]
Hi, thank you for the beautiful work.
I'm trying to use tutorials to familiarize myself with code and use it.
I run the tutorial and get the error, possibly the code is ahead of tutorial.
What do you suggest?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[17], line 7
      5 # Initialize the DRR module for generating synthetic X-rays
      6 device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
----> 7 drr = DRR(
      8     subject,  # A torchio.Subject object storing the CT volume, origin, and voxel spacing
      9     sdd=1020,  # Source-to-detector distance (i.e., the C-arm's focal length)
     10     height=200,  # Height of the DRR (if width is not seperately provided, the generated image is square)
     11     delx=2.0,  # Pixel spacing (in mm)
     12 ).to(device)

TypeError: DRR.__init__() missing 2 required positional arguments: 'spacing' and 'sdr'

**Comment by eigenvivek** [comment]
Hi @sarbabi, thank you for the kind words.

I am currently in the middle of a big overhaul of the library for `v0.4.0`. The docs that you're running are ahead of the current version on PyPi. (I really need to figure out how to serve multiple versions of the documentation on the same site.)

In my opinion, the best solution would be to install the latest version of DiffDRR directly from the github page. It's simple to do so, just clone the repo and pip install:
```zsh
git clone https://github.com/eigenvivek/DiffDRR.git --depth 1
cd DiffDRR
pip install -e '.[dev]'
```

Then all the tutorial notebooks should run.

**Comment by sarbabi** [comment]
Thank you, resolved.
