### ISSUE TITLE
bigger field of view

### ISSUE THREAD

**Issue by sarbabi** [eigenvivek/DiffDRR#226]
Hi.
I'm trying to do 2D3D registration. 
The field of view is relatively bigger as focus is on whole lower extremity. one example Xray:
![xray](https://github.com/eigenvivek/DiffDRR/assets/21973354/75adfb6e-3854-4443-b5d7-f336c7cc0f50)

generating DRR with default parameters as in tutorial results in this view:
![image](https://github.com/eigenvivek/DiffDRR/assets/21973354/8c1d88d4-ac32-4127-83c0-de0f2e234d66)

If I change height to 600 instead, I get this view:
![image](https://github.com/eigenvivek/DiffDRR/assets/21973354/14d99676-3b52-4337-9b5a-5e5ea124c49c)
which covers the whole lower extremity field of view, but does not look sharp probably as this way height is too much. also this is slower, takes around 20s for image which will probably make registration optimization slow.

what do you suggest in this case of images with bigger field of view?

**Comment by eigenvivek** [comment]
Hi @sarbabi, there's a few things you can do:

1. You can set the height and width in `DRR(height=..., width=...)` separately. That is, you don't have to render all the black space to the left and right of the patient. 
2. You can downsample the real X-ray to have a smaller resolution and render the DRR at this smaller resolution.

Also 20s for a 600x600 image seems slow. Are you using a GPU?

**Comment by sarbabi** [comment]
Hi @eigenvivek , Thank you. The "width" solution works well in speeding up. I'm using GPU and now the time is ~1s.

**Comment by eigenvivek** [comment]
Glad that helped. On a NVIDIA 2080Ti, I've benchmarked DiffDRR as rendering a 600x600 DRR in ~200 ms (see [this tutorial](https://vivekg.dev/DiffDRR/tutorials/timing.html#memory-constraints)). You might be able to speed up your rendering further using the `patch_size` argument. Let me know if you have any other questions!
