### ISSUE TITLE
Application of external matrices in real X-ray

### ISSUE THREAD

**Issue by shenao1994** [eigenvivek/DiffDRR#233]
Hi！I am currently doing the registration of real X-ray，and two camera external matrices are provided in the data. The coordinate system of the camera can be transformed by using the external matrices to register the two views. However, after the application of external matrices , the position of the camera changed, but the CT was still in the original position. How can I modify the code in **diffdrr** and apply the external matrices to CT. I hope I can get your help, thank you!
![微信截图_20240508104844](https://github.com/eigenvivek/DiffDRR/assets/28835780/745f72a1-d258-46c5-bdc3-e9908dba4213)

**Comment by eigenvivek** [comment]
Hi @shenao1994, DiffDRR only applies transformations to the cameras, not the CT. I assume the CT is placed at the isocenter of world coordinates. Do you also want the CT to be transformed by the same matrices?

Also, for the PyVista plot, there's an option called [`pyvista.Plotter.show_grid`](https://docs.pyvista.org/version/stable/api/plotting/_autosummary/pyvista.Plotter.show_grid.html), which will add axis labels to the 3D grid. Could you add this so I can see where the various objects are located? Thanks.

**Comment by shenao1994** [comment]
> Hi @shenao1994, DiffDRR only applies transformations to the cameras, not the CT. I assume the CT is placed at the isocenter of world coordinates. Do you also want the CT to be transformed by the same matrices?
> 
> Also, for the PyVista plot, there's an option called [`pyvista.Plotter.show_grid`](https://docs.pyvista.org/version/stable/api/plotting/_autosummary/pyvista.Plotter.show_grid.html), which will add axis labels to the 3D grid. Could you add this so I can see where the various objects are located? Thanks.

Yes, I want the CT to be transformed by the same matrices. Should I perform some transformation operations on volume?

OK. This is a plot after adding axis labels.
![微信截图_20240509092318](https://github.com/eigenvivek/DiffDRR/assets/28835780/fb45b286-1216-40e6-9589-80ec35eb433a)

**Comment by eigenvivek** [comment]
OK I see. DiffDRR doesn't apply transformations to the CTs, only the camera. In theory, if you wanted to apply transform T to the CT, you could achieve the same effect by applying T^-1 to the cameras.

PyVista has another feature called `pyvista.DataSetFilters.transform`. I think the api is something like `mesh.transform(T)`, where `T` is the 4x4 affine transformation matrix. If that moves the CT to the right position relative to your cameras in the 3D rendering, then applying T^-1 to the camera matrices should work.

**Comment by shenao1994** [comment]
> OK I see. DiffDRR doesn't apply transformations to the CTs, only the camera. In theory, if you wanted to apply transform T to the CT, you could achieve the same effect by applying T^-1 to the cameras.
> 
> PyVista has another feature called `pyvista.DataSetFilters.transform`. I think the api is something like `mesh.transform(T)`, where `T` is the 4x4 affine transformation matrix. If that moves the CT to the right position relative to your cameras in the 3D rendering, then applying T^-1 to the camera matrices should work.

Thank you very much for your help. I will give it a try!

**Comment by eigenvivek** [comment]
Hi @shenao1994 , closing this for now, feel free to reopen if you're still having issues!
