### ISSUE TITLE
DRR.perspective_projection function

### ISSUE THREAD

**Issue by coolteemf** [eigenvivek/DiffDRR#235]
Hi,
First of all, thank you for this great package, it is indeed quite fast !

I'm trying to understand how the projection geometry works in your framework, and for this I've used the DRR.perspective_projection function to project 3D points to 2D points.
However, I'm getting unexpected results, and I'm not sure how the pose matrix is used in the renderer.
What I'm seeing is that the pose is used to compute the position of the source and the target and that the projection rays are then computed from that.
I'm more used to the rays being computed with something like ray = (camera.intrinsic . camera.extrinsic . volume.affine)^-1 . point_2D , so I'm not sure how it translates in your framework.

Here is the code I've used with the example ct:
```
subject = load_example_ct(bone_attenuation_multiplier=1.0)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
drr = DRR(
    subject,  # A torchio.Subject object storing the CT volume, origin, and voxel spacing
    sdd=1020,  # Source-to-detector distance (i.e., the C-arm's focal length)
    height=200,  # Height of the DRR (if width is not seperately provided, the generated image is square)
    delx=2.0,  # Pixel spacing (in mm)
    reverse_x_axis=False
).to(device)
points = torch.tensor([[[-10.884, -7.597, 135.906],
                        [-108., -7.5, -307.],
                        [57, -17., -249.]
                        ]], device=device)
p2d = drr.perspective_projection(convert(rotations, translations, parameterization="euler_angles", convention="ZXY"), 
      points)
print(points)
print(p2d)
axs = plot_drr(img, ticks=False)
# axs[0].scatter(p2d.squeeze().cpu().numpy()[1], p2d.squeeze().cpu().numpy()[0], c="r", s=100)
for p in p2d.squeeze().cpu().numpy():
    axs[0].scatter(p[1], p[0], c="r", s=100)
plt.show()
```
Here, the 3D points are inside the organs, so the 2D points should be superposed with the organs, but they aren't:
![image](https://github.com/eigenvivek/DiffDRR/assets/67541941/c73a86a8-a873-452b-a952-7102df6ae55a)

Do you have an idea how I could derive the correct 2D/3D projection matrix from the pose, volume affine and intrinsic matrix ?

**Comment by eigenvivek** [comment]
Hi @coolteemf , thank you for the kind words.

Perspective projection in DiffDRR works exactly as you described, just implemented differently. See the implementation here:
https://github.com/eigenvivek/DiffDRR/blob/bc2d8695ca1bb0cc9b10d31a2391814e825e3d91/diffdrr/drr.py#L181-L195

- The `extrinsic` matrix is simply constructed from the `rotation`/`translation` that you provide
- The `intrinsic` matrix is constructed from the parameters you supply to the constructor of `DRR` (see below)

https://github.com/eigenvivek/DiffDRR/blob/bc2d8695ca1bb0cc9b10d31a2391814e825e3d91/diffdrr/utils.py#L44-L64

I assume that the coordinates you supply are already in world coordinates, so you have to transform voxel indices with the affine matrix yourself before passing them to `drr.perspective_projection`.

**Comment by coolteemf** [comment]
Thank you very much @eigenvivek !
I found out what the issue was.
The read function transforms the volume affine to canonical space.
To transform the points from the original space to the canonical space, I simply did:
```
aff2subj_mat = torch.tensor(subject.get_images()[0].affine) @ affine.inverse()
points = torch.einsum('...ac, ...c -> ...a', aff2subj_mat, points)
```
With affine the original affine in the nifti file.
Got the expected results:
![image](https://github.com/eigenvivek/DiffDRR/assets/67541941/d1c5d979-bbf8-47fd-93d0-4d48a017ad20)

Given the transformation applied in the read function, I assume it is necessary to convert the volume affine to canonical space for the renderer to work correctly ?

**Comment by eigenvivek** [comment]
Hi @coolteemf , glad you were able to fix your issue!

Yes, DiffDRR canonicalizes all input volumes to be in the RAS+ space. This is done to make the renderings consistent all input volumes. I added this because some of the volumes I had were in LPS+ and some were in RAS+, so rendering DRRs from the same pose gave very different results. You shouldn't have to change anything in your raw data, however, since `torchio` handles all of this internally:
https://github.com/eigenvivek/DiffDRR/blob/bc2d8695ca1bb0cc9b10d31a2391814e825e3d91/diffdrr/data.py#L130-L147

So you're right that the affine matrix needs to be applied to fiducial markers. Currently, the package doesn't have any capabilities to read fiducials, but that would be a good thing for me to add to the `diffdrr.data.read` function. Thanks for the issue!
