### ISSUE TITLE
Extrinsic passed to the DRR module

### ISSUE THREAD

**Issue by haarisr** [eigenvivek/DiffDRR#252]
I am not sure what is the extrinsic passed to the DRR module.

It seems that is `isocenter_from_camera`. Usually, extrisnics are from some world frame to the camera frame. But I believe the DRR module takes the inverse?

Also in `v0.4`, I believe the world is at the isocenter of the CT space. It get's pretty hard to do anything with extrinsics in RAS space, since the conversion is lost is in `canocalize` when `image.affine` is overwritten.

**Comment by shenao1994** [comment]
Currently, we have applied **DiffDRR** for dual view registration in real-world scenarios. After applying the external parameters of the camera, imaging can be performed.
![image](https://github.com/eigenvivek/DiffDRR/assets/28835780/983d78ac-86a9-4b80-a754-70026590ce28)

**Comment by eigenvivek** [comment]
Hi @haarisr , you're right that in the newest version, `v0.4.0`, I use `canonicalize` to move the CT such that its isocenter is at the origin in world coordinates. 

Yes, DiffDRR typically takes the inverse transform. That's because we use a CT-centric frame of reference. In frame of reference where the camera is fixed, the transform corresponds to moving the CT. The inverse transform moves the camera.

If the original world coordinate system is useful to you, we should maybe look at adding an `uncanonicalize` function that returns you to those coordinates. I like translating everything to the isocenter because it makes camera poses more translatable across datasets.

**Comment by haarisr** [comment]
Maybe you could just expose a transform/function of RAS to isocenter, this way you could avoid the `fiducials` parameter. It would help with any information you obtain from the CT in RAS space

Also, curious to know the use case of the same camera pose for different datasets. How would you compare the DRR's of different subjects with different isocenters?

**Comment by eigenvivek** [comment]
> Maybe you could just expose a transform/function of RAS to isocenter, this way you could avoid the fiducials parameter. It would help with any information you obtain from the CT in RAS space

That's a good idea. Would totally merge a PR that fits your needs. 

> Also, curious to know the use case of the same camera pose for different datasets. How would you compare the DRR's of different subjects with different isocenters?

Purpose isn't to compare DRRs across subjects, but rather to unify units. I.e., 30 degree RAO projection means the same thing for every CT.

**Comment by haarisr** [comment]
Hi 

I'm facing some issue going from a deepdrr extrinsic to a diffdrr one. The drr generated by diffdrr is rotated by 90 degrees. 

When trying to rotate the CT 90 degrees and using the visualization tools, the DRR texture in the 3D view appears to be the same as when not rotating the CT.

However when viewing the 2d image, there's a rotation.

**Comment by eigenvivek** [comment]
> The drr generated by diffdrr is rotated by 90 degrees.

Sounds like a change of basis (i.e., which axis we call x- and y- is swapped). Do you have any examples?

> When trying to rotate the CT 90 degrees and using the visualization tools, the DRR texture in the 3D view appears to be the same as when not rotating the CT.

How are you rotating the CT?

**Comment by haarisr** [comment]
> Sounds like a change of basis (i.e., which axis we call x- and y- is swapped). Do you have any examples?

How would you like to see the example?

> How are you rotating the CT?

Just multiplying the extrinsic with a rotation of 90 degrees about S axis in RAS space of the CT.
