### ISSUE TITLE
exponential decay for synthetic radiographs

### ISSUE THREAD

**Issue by sergiosgatidis** [eigenvivek/DiffDRR#273]
Hello, 
This is a great project and extremely helpful for many different research directions.
I have a question related to the generated radiographs. It seems that these represent the projected sum of densities along a ray. Should there not be an additional exponential decay function to generate the actual xray image? Maybe I am missing something. 
Thanks!

**Comment by eigenvivek** [comment]
Hi @sergiosgatidis , very happy to hear DiffDRR has been useful for some of your projects!

You're right that the DRRs rendered in this package is the projected sum of densities along each ray. This corresponds to the linear attenuation form of an X-ray image. Specifically, this is the rendering equation computed by DiffDRR:
<img width="452" alt="image" src="https://github.com/eigenvivek/DiffDRR/assets/29757116/79ed7026-e911-4973-8430-636306a5c97c">
where **p** and **s** are the target and source coordinates of a ray in world coordinates, respectively, **V** is the CT volume, and *I_0* is the initial energy of each ray.

This can easily be converted to the exponential form with the following formula:

<img width="237" alt="image" src="https://github.com/eigenvivek/DiffDRR/assets/29757116/190d45d9-abfe-4e89-83e8-8557aa66a624">

Appendix E of the [DiffPose](https://arxiv.org/pdf/2312.06358#page=15.66) paper derives these forms in more detail. Please let me know if you have more questions!

**Comment by eigenvivek** [comment]
closing for now, feel free to reopen if you have any more issues/questions
