### ISSUE TITLE
Expose/set persistent to False

### ISSUE THREAD

**Issue by haarisr** [eigenvivek/DiffDRR#284]
https://github.com/eigenvivek/DiffDRR/blob/9bda058241aa084f83dcc73c2eeb2927f1715481/diffdrr/drr.py#L66-L71

The `DRR` module requires the `subject` to be passed in. 

If you have a model, that uses the rendering module, then when saving the module, the state dict contains the entire uncompressed CT. 

By using `persisent=False` in `register_buffer`, the CT is part of the module, but not the state dict.

We could either expose the value or set it to False internally.

**Comment by eigenvivek** [comment]
Sure good idea! Why don't we add a `persistent` flag to the `DRR` constructor and pass that directly to the density, spacing, origin, and mask?

**Comment by haarisr** [comment]
> Sure good idea! Why don't we add a `persistent` flag to the `DRR` constructor and pass that directly to the density, spacing, origin, and mask?

Sure. Just concerned if a use case comes up for a persisent flag for each parameter later on. But for now, we can just say that one flag applies to all parameters.

Will make a PR later on for this
