### ISSUE TITLE
Understanding Parameters for DRR module

### ISSUE THREAD

**Issue by Alookima21** [eigenvivek/DiffDRR#306]
When initialising the DRR module, we provide parameters including sdd, height and delx. I wanted to know what sdd exactly is/represents and what unit of measurement it uses? Is it a unit used elsewhere in medical imaging, or just in this drr module?

**Comment by eigenvivek** [comment]
all units in diffdrr are millimeters

sdd = source to detector distance
this is common in x-ray and ct imaging. it's the distance between the x-ray source and the closest point on the detector plane. most sdd's on commercial imaging systems are ~1 meter

it's also sometimes referred to as the source to image distance https://dicom.innolitics.com/ciods/computed-radiography-image/cr-image/00181110

**Comment by Alookima21** [comment]
I also wanted to ask the units for rotations (Degrees or radians). I want to generate a variety Xrays that account for slight rotations from the patient; this is keeping in mind that not all XRays provide a perfectly straight view perpendicular to the backbone. I found that the Z axis rotation value allows introducing such variability; is there any range within which I should work, or should I just appy trial and error?

**Comment by eigenvivek** [comment]
units for rotation are in radians

zero radians means you are looking perfectly straight at the patient

rotating about the z-axis in a range of [-pi / 2, pi / 2] will give you a 180 degree view, from 90 degrees right to 90 degrees left
