### ISSUE TITLE
Could not infer dtype of numpy.float32

### ISSUE THREAD

**Issue by bs1119** [eigenvivek/DiffDRR#333]
Tryin to run the tutorial on gpu with CUDA 12.1. Run into the following error: 

002_ct_tomo_registration_py39_cuda121\lib\site-packages\torchio\data\image.py:603: UserWarning: Error loading image with SimpleITK:
Could not infer dtype of numpy.float32

File ~\AppData\Local\anaconda3\envs\002_ct_tomo_registration_py39_cuda121\lib\site-packages\torchio\data\io.py:59, in _read_nibabel(path)
     57     data = data.transpose(3, 0, 1, 2)
     58 data = check_uint_to_int(data)
---> 59 tensor = torch.as_tensor(data)
     60 affine = img.affine
     61 return tensor, affine

RuntimeError: Could not infer dtype of numpy.float32

**Comment by eigenvivek** [comment]
sounds like a torchio issue. have you checked their repo for similar issues?

**Comment by eigenvivek** [comment]
I'm able to run the tutorial with `torchio=0.19.7` and `numpy<2`. My best bet is a numpy incompatibility issue. If the issue persists, feel free to reopen.
