### ISSUE TITLE
CT spacing

### ISSUE THREAD

**Issue by fedeface98** [eigenvivek/DiffDRR#337]
Hi,

I have a doubt regarding the spacing of the CT scan. Is this used somehow in the translation of the C-Arm? Because I saw in the paper that the isocenter translation is defined as the number of voxel * spacing of the CT. I was wondering if I should have the same spacing in different patients to have comparable translation.

Thanks a lot for your amazing work.

Federica

**Comment by eigenvivek** [comment]
hi Federica, the CT spacing isn't used in the C-arm translation. the C-arm spacing is applied to the points along each ray, so as to find where in the volume they lie.

the current implementation computes the same integral laid out in the paper, but the steps are different. now, we use the inverse of the affine matrix to map sampled points from world coordinates to voxel space. same operation, just more efficient :)
