### ISSUE TITLE
the parameters in diffdrr has changed

### ISSUE THREAD

**Issue by asjeff** [eigenvivek/DiffDRR#340]
when I use "pip install diffdrr", the parameters in its code in drr.py has changed. In the initialization of DRR, it is the sdr parameter and spacing parameter, not the sdd parameter.  And then the tutorial can't be executed successfully.

**Comment by eigenvivek** [comment]
hi @asjeff can you make sure you've installed the latest version of diffdrr?

**Comment by asjeff** [comment]
> hi @asjeff can you make sure you've installed the latest version of diffdrr?

I am using a version that matches the code in diffpose

**Comment by eigenvivek** [comment]
ah that uses an older version of diffdrr with a different api. you can roll the github repo back to that version for tutorial code.
