### ISSUE TITLE
#TypeError: any() received an invalid combination of arguments - got (dim=list, )

### ISSUE THREAD

**Issue by YCIT-Coder** [eigenvivek/DiffDRR#341]
I executed the code in ReadMe and had some problems.
The operation result shows the following contents:
TypeError: any() received an invalid combination of arguments - got (dim=list, ), but expected one of:
 * ()
      didn't match because some of the keywords were incorrect: dim
 * (int dim, bool keepdim)
 * (name dim, bool keepdim)

The error appears in the renderers.py file, line 119, the call of tensor.any(). The dim parameter passes in a list, but the specified dim parameter is type int in the pytorch official API. Please help the project developer to solve it, thank you.

**Comment by YCIT-Coder** [comment]
OK. The version of Pytorch should be 2.2+.

**Comment by eigenvivek** [comment]
correct, I'll update the `environment.yml`
