### ISSUE TITLE
Bug: Density calculation is wrong if orientation of volume and mask differs

### ISSUE THREAD

**Issue by LukasNickel** [eigenvivek/DiffDRR#346]
Hi!

Huge fan of the work you did here, really makes these things much easier for someone without a huge medical background :)

I am currently testing the DRR-procedure with an open source CT-dataset and some segmentations masks generated using TotalSegmentator. During that, I ran into some unexpected behaviour. It turns out, that TotalSegmentator (at least in the version used by me) always saves the masks in LAS+ orientation, presumably because they want to make sure, that the orientation is always the same in the network and they don't bother to transform it back to the input data's orientation.

This screws over the density calculation in `read`, because `DiffDRR` never actually checks the orientation of the input arrays. In particular, this operation:
https://github.com/eigenvivek/DiffDRR/blob/30b59533992055c6c5dca9e5f8c9c1187ffba5b1/diffdrr/data.py#L141
only makes sense if the two arrays have the same orientation.

This only matters if one wants to create DRRs of individual bones/masked regions AND the orientation of the CT data and mask is not the same, but then it can be really annoying to debug, especially if you mask only the left/right bones and have a somewhat symmetrical field of view in the CT (ask me how I know...).

The easiest way to avoid those issues is probably to use `torchio`'s `ToCanonical()` everywhere, but if that is not acceptable for whatever reason, it can also be coded manually for the mask only.

**Comment by eigenvivek** [comment]
Hi @LukasNickel that's an annoying issue, sorry about that...

We previously used `ToCanonical`, but it caused issues for some downstream tasks, so it was deprecated (see https://github.com/eigenvivek/DiffDRR/pull/283).

I guess the simplest solution would be to add a function that reorients the `mask` to the same orientation as the `volume`, if they're not the same. Do you think this would solve your problem?

**Comment by LukasNickel** [comment]
I have a workaround for my own issue, so I am not in dire need of an upstream solution :)
As I convert to canonical anyway, I just recalculate the density before rendering the DRR.

If you want to avoid ToCanonical for whatever reason, then reorienting the mask is probably the best solution.

**Comment by eigenvivek** [comment]
Great! I'll leave this issue open for now in case anyone else runs into this issue / wants to fix it.

**Comment by LukasNickel** [comment]
Ok, maybe I can even find some time myself :)
