### ISSUE TITLE
Remove whitespace around saved gifs

### ISSUE THREAD

**Issue by eigenvivek** [eigenvivek/DiffDRR#53]
Something in [animation function](https://github.com/v715/DiffDRR/blob/f400866d32c43437a9a9662f5550c350d46fa7cb/diffdrr/visualization/animation.py#L25-L43) is producing too much whitespace around saved GIFs

Need to figure out how to remove this

**Comment by v715** [comment]
https://stackoverflow.com/questions/73543900/how-to-remove-whitespace-from-animated-matplotlib-gifs/73544987#73544987
