### ISSUE TITLE
Use two or more GPUs

### ISSUE THREAD

**Issue by zenghy96** [eigenvivek/DiffDRR#92]
Hi, I wonder how to use the DiffDRR on two or more GPUs.

**Comment by eigenvivek** [comment]
Hi, I do not exactly know how to use DiffDRR with multiple GPUs. H

**Comment by eigenvivek** [comment]
TODO: change the `DRR` module to accept batches of target points

multiple batches of points can be loaded onto different GPUs

can also allow for the processing of larger DRRs in series and avoid memory errors

**Comment by eigenvivek** [comment]
I think this is going to be too complicated to implement, so I'm closing the PR at this time.

To do this, you'd need to send copies of the volume and targets to multiple GPUs, aggregate the results, and combine to form a single DRR.

For now, I think using the `patch_size` setting should be sufficient. It allows the user to compute DRRs of arbitrary sizes by computing patches in series (see [this example in the docs](https://vivekg.dev/DiffDRR/tutorials/timing.html#memory-constraints))
